VCS_DB_TABLE_NAME: str = "vcs_metadata"
CLOC_DB_TABLE_NAME: str = "cloc"
LOC_DB_TABLE_NAME: str = "loc"
COMMIT_HASH_TO_PRODUCTIVITY_BUCKET_MAP_TABLE_NAME: str = (
    "commit_hash_to_productivity_map"
)
COMMIT_HASH_TO_DEVELOPER_COUNT_BUCKET_MAP_TABLE_NAME: str = (
    "commit_hash_to_developer_count_map"
)
COMMIT_HASH_TO_BUS_FACTOR_BUCKET_MAP_TABLE_NAME: str = "commit_hash_to_bus_factor_map"
ISSUE_ID_TO_ISSUE_COUNT_BUCKET_MAP_TABLE_NAME: str = "issue_id_to_issue_count_map"
ISSUE_ID_TO_ISSUE_SPOILAGE_BUCKET_MAP_TABLE_NAME: str = "issue_id_to_issue_spoilage_map"
ISSUE_TRACKER_DB_TABLE_NAME: str = "issue_tracker"

DAILY_PRODUCTIVITY_DB_TABLE_NAME: str = "daily_productivity"
WEEKLY_PRODUCTIVITY_DB_TABLE_NAME: str = "weekly_productivity"
TWO_WEEK_PRODUCTIVITY_DB_TABLE_NAME: str = "two_week_productivity"
MONTHLY_PRODUCTIVITY_DB_TABLE_NAME: str = "monthly_productivity"
TWO_MONTH_PRODUCTIVITY_DB_TABLE_NAME: str = "two_month_productivity"
THREE_MONTH_PRODUCTIVITY_DB_TABLE_NAME: str = "three_month_productivity"
SIX_MONTH_PRODUCTIVITY_DB_TABLE_NAME: str = "six_month_productivity"
ANNUAL_PRODUCTIVITY_DB_TABLE_NAME: str = "annual_productivity"

DAILY_DEVELOPER_COUNT_DB_TABLE_NAME: str = "daily_developer_count"
WEEKLY_DEVELOPER_COUNT_DB_TABLE_NAME: str = "weekly_developer_count"
TWO_WEEK_DEVELOPER_COUNT_DB_TABLE_NAME: str = "two_week_developer_count"
MONTHLY_DEVELOPER_COUNT_DB_TABLE_NAME: str = "monthly_developer_count"
TWO_MONTH_DEVELOPER_COUNT_DB_TABLE_NAME: str = "two_month_developer_count"
THREE_MONTH_DEVELOPER_COUNT_DB_TABLE_NAME: str = "three_month_developer_count"
SIX_MONTH_DEVELOPER_COUNT_DB_TABLE_NAME: str = "six_month_developer_count"
ANNUAL_DEVELOPER_COUNT_DB_TABLE_NAME: str = "annual_developer_count"

DAILY_ISSUE_COUNT_DB_TABLE_NAME: str = "daily_issue_count"
WEEKLY_ISSUE_COUNT_DB_TABLE_NAME: str = "weekly_issue_count"
TWO_WEEK_ISSUE_COUNT_DB_TABLE_NAME: str = "two_week_issue_count"
MONTHLY_ISSUE_COUNT_DB_TABLE_NAME: str = "monthly_issue_count"
TWO_MONTH_ISSUE_COUNT_DB_TABLE_NAME: str = "two_month_issue_count"
THREE_MONTH_ISSUE_COUNT_DB_TABLE_NAME: str = "three_month_issue_count"
SIX_MONTH_ISSUE_COUNT_DB_TABLE_NAME: str = "six_month_issue_count"
ANNUAL_ISSUE_COUNT_DB_TABLE_NAME: str = "annual_issue_count"

DAILY_ISSUE_SPOILAGE_DB_TABLE_NAME: str = "daily_issue_spoilage"
WEEKLY_ISSUE_SPOILAGE_DB_TABLE_NAME: str = "weekly_issue_spoilage"
TWO_WEEK_ISSUE_SPOILAGE_DB_TABLE_NAME: str = "two_week_issue_spoilage"
MONTHLY_ISSUE_SPOILAGE_DB_TABLE_NAME: str = "monthly_issue_spoilage"
TWO_MONTH_ISSUE_SPOILAGE_DB_TABLE_NAME: str = "two_month_issue_spoilage"
THREE_MONTH_ISSUE_SPOILAGE_DB_TABLE_NAME: str = "three_month_issue_spoilage"
SIX_MONTH_ISSUE_SPOILAGE_DB_TABLE_NAME: str = "six_month_issue_spoilage"
ANNUAL_ISSUE_SPOILAGE_DB_TABLE_NAME: str = "annual_issue_spoilage"

ANNUAL_BUS_FACTOR_DB_TABLE_NAME: str = "annual_bus_factor"
DAILY_BUS_FACTOR_DB_TABLE_NAME: str = "daily_bus_factor"
MONTHLY_BUS_FACTOR_DB_TABLE_NAME: str = "monthly_bus_factor"
SIX_MONTH_BUS_FACTOR_DB_TABLE_NAME: str = "six_month_bus_factor"
THREE_MONTH_BUS_FACTOR_DB_TABLE_NAME: str = "three_month_bus_factor"
TWO_MONTH_BUS_FACTOR_DB_TABLE_NAME: str = "two_month_bus_factor"
TWO_WEEK_BUS_FACTOR_DB_TABLE_NAME: str = "two_week_bus_factor"
WEEKLY_BUS_FACTOR_DB_TABLE_NAME: str = "weekly_bus_factor"

DAILY_ISSUE_DENSITY_DB_TABLE_NAME: str = "daily_issue_density"
WEEKLY_ISSUE_DENSITY_DB_TABLE_NAME: str = "weekly_issue_density"
TWO_WEEK_ISSUE_DENSITY_DB_TABLE_NAME: str = "two_week_issue_density"
MONTHLY_ISSUE_DENSITY_DB_TABLE_NAME: str = "monthly_issue_density"
TWO_MONTH_ISSUE_DENSITY_DB_TABLE_NAME: str = "two_month_issue_density"
THREE_MONTH_ISSUE_DENSITY_DB_TABLE_NAME: str = "three_month_issue_density"
SIX_MONTH_ISSUE_DENSITY_DB_TABLE_NAME: str = "six_month_issue_density"
ANNUAL_ISSUE_DENSITY_DB_TABLE_NAME: str = "annual_issue_density"
