from collections import namedtuple

from prime_vx.db import (
    ANNUAL_PRODUCTIVITY_DB_TABLE_NAME,
    DAILY_PRODUCTIVITY_DB_TABLE_NAME,
    MONTHLY_PRODUCTIVITY_DB_TABLE_NAME,
    SIX_MONTH_PRODUCTIVITY_DB_TABLE_NAME,
    THREE_MONTH_PRODUCTIVITY_DB_TABLE_NAME,
    TWO_MONTH_PRODUCTIVITY_DB_TABLE_NAME,
    TWO_WEEK_PRODUCTIVITY_DB_TABLE_NAME,
    WEEKLY_PRODUCTIVITY_DB_TABLE_NAME,
)

BUCKET_STOR = namedtuple(
    typename="BUCKET_STOR",
    field_names=[
        DAILY_PRODUCTIVITY_DB_TABLE_NAME,
        WEEKLY_PRODUCTIVITY_DB_TABLE_NAME,
        TWO_WEEK_PRODUCTIVITY_DB_TABLE_NAME,
        MONTHLY_PRODUCTIVITY_DB_TABLE_NAME,
        TWO_MONTH_PRODUCTIVITY_DB_TABLE_NAME,
        THREE_MONTH_PRODUCTIVITY_DB_TABLE_NAME,
        SIX_MONTH_PRODUCTIVITY_DB_TABLE_NAME,
        ANNUAL_PRODUCTIVITY_DB_TABLE_NAME,
    ],
)

COMMIT_HASH_TO_BUCKET_MAPPING: dict[str, BUCKET_STOR] = {}
